# Categories to filter (empty list = all CS categories)
# Options: Artificial Intelligence, Computation and Language, Machine Learning, etc.
categories:
  ["Computer Vision and Pattern Recognition", "Artificial Intelligence"]

# Model to use for relevancy scoring
# Examples: deepseek-chat, gpt-4, gpt-4-turbo
model: "deepseek-chat"

# Relevance score threshold (1-10)
# Papers scoring below this will be filtered out
threshold: 7

# Filtering criteria (natural language)
# Leave empty to skip filtering and list all papers
standard: |
  和 VLN (Vision-Language Navigation) / VLA (Vision Language Action) 相关；
  其中和“无图目标导航”任务相关的工作优先级更高；
  重点关注室内场景下的导航任务；
  用中文回答原因。
